### ISSUE TITLE
No support for decompress - Zeros Data

### ISSUE THREAD

**Issue by halotroop2288** [sethfoxen/maxcsoGUI#1]
A quite alarming side effect of using this program incorrectly is when trying to use it to decompress CSOs back into ISOs. Instead of warning the user, or disallowing this type of use, the program just tries to write over the selected CSO files, and then says "success" when the files have been overwritten with zero data.

I recommend disallowing the import of non-ISO files until support for decompression can be added. Or instead, just adding support for decompression, and detecting which type of file is before each operation to prevent errors.

**Comment by RinMaru** [comment]
it can decompress but its broken atm not sure why but it did work at one point this is more a issue for Maxcso and not the GUI i believe

**Comment by sethfoxen** [comment]
So sorry for the very VERY late reply. I CAN confirm that this was an issue with maxcso itself, and the GUI had nothing to do with this.
